on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: CI

jobs:
  bom:
    name: Bill of Materials
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: newam
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#bom -L
      - name: deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
          force_orphan: true
